services:
  main:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./projects:/app/projects
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
